apiVersion: apps/v1

kind: Deployment

metadata:
  name: app-deployment

specs:
  replicas: 2

  selector:
    matchLabels:
      app: simple-app

  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: node-container
          image: fradriks/devops-practices
          ports:
            - containerPort: 4000
